pool:
    vmImage: 'Ubuntu 16.04'

variables:
    Version: '3.0.$(Build.BuildId)'
    ImageName: biowareru/bioengine-brc-games:$(Version)

steps:
    - task: UseDotNet@2
      inputs:
          packageType: sdk
          version: 3.0.100-preview5-011568
          includePreviewVersions: true

    - task: UseNode@1
      inputs:
        version: '11.x'
        checkLatest: true
        
    - task: DotNetCoreCLI@2
      inputs:
          command: restore
          projects: '**/*.csproj'
          feedsToUse: 'select'
          verbosityRestore: 'minimal'
          vstsFeed: 'BioEngine'

    - task: Bash@3
      inputs:
        targetType: 'inline'
        workingDirectory: 'src/BioEngine.BRC.Games'
        script: |
            npm ci
            npm run build-prod

    - task: DotNetCoreCLI@2
      inputs:
          command: custom
          custom: publish
          publishWebProjects: false
          zipAfterPublish: false
          modifyOutputPath: false
          arguments: '--no-restore -c Release --output ./publish'
          projects: '**/*.csproj'

    - script: |
          docker build -f src/BioEngine.BRC.Games/Dockerfile ./publish -t $(ImageName)
      displayName: 'build docker image'

    - script: |
          docker login -u $(dockerId) -p $(dockerPswd)
      displayName: 'login to docker hub'

    - script: |
          docker push $(ImageName)
      displayName: 'push image to docker hub'
    
