pool:
    vmImage: 'Ubuntu 16.04'

variables:
    Version: '3.0.$(Build.BuildId)'
    ImageName: biowareru/bioengine-brc-games:$(Version)

steps:
    - task: UseDotNet@2
      displayName: 'install .net core 3.0'
      inputs:
          packageType: sdk
          version: 3.0.100-preview6-012264
          includePreviewVersions: true

    - task: UseNode@1
      displayName: 'install node'
      inputs:
          version: '11.x'
          checkLatest: true

    - task: DotNetCoreCLI@2
      displayName: 'dotnet restore'
      inputs:
          command: restore
          projects: '**/*.csproj'
          feedsToUse: 'select'
          verbosityRestore: 'minimal'
          vstsFeed: 'BioEngine'

    - task: Npm@1
      displayName: 'install npm packages'
      inputs:
          command: 'custom'
          customCommand: 'ci'
          workingDir: 'src/BioEngine.BRC.Games'

    - task: Npm@1
      displayName: 'build frontend'
      inputs:
          command: 'custom'
          customCommand: 'run build-prod'
          workingDir: 'src/BioEngine.BRC.Games'

    - task: DotNetCoreCLI@2
      displayName: 'publish app'
      inputs:
          command: custom
          custom: publish
          publishWebProjects: false
          zipAfterPublish: false
          modifyOutputPath: false
          arguments: '--no-restore -c Release --output ./publish'
          projects: '**/*.csproj'

    - task: Docker@2
      displayName: 'build and push image'
      inputs:
          containerRegistry: 'BioWareRU DockerHub'
          repository: 'biowareru/bioengine-brc-games'
          command: 'buildAndPush'
          Dockerfile: 'src/BioEngine.BRC.Games/Dockerfile'
          buildContext: './publish'
          tags: '$(Version)'
    
