name: Build

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest
        container: ghcr.io/sitkoru/actions-container
        env:
            PROJECT: "BioEngine.BRC.Games"
        steps:
            -   uses: actions/checkout@v2
            -   name: Install .NET
                uses: actions/setup-dotnet@v1
                with:
                    dotnet-version: '3.1.x'
            -   name: Install NodeJS
                uses: actions/setup-node@v2.1.5
                with:
                    node-version: '14'
            -   name: Build JS
                working-directory: src/${{ env.PROJECT}}
                run: |
                    whoami
                    ls -la
                    mkdir -p /__w/BioEngine.BRC.Games/BioEngine.BRC.Games/src/BioEngine.BRC.Games/node_modules/node-sass/vendor/linux-x64-83
                    node -v
                    npm -v
                    npm i
                    npm run build
            -   name: Publish app
                run: dotnet publish src/${{ env.PROJECT}}/${{ env.PROJECT}}.csproj --output /app/ --configuration Release
